const Unidades = () => {
    
    const unidadesArray = [
        "TTT333",
        "DGP",
        "CVP",
        "CIAP",
        "DAL",
        "CITEL",
        "CSM",
        "DGEC",
        "CFAP",
        "APM",
        "DF",
        "EMG",
        "CORREG",
        "GABCG",
        "GABSUBCG",
        "CONJUR",
        "CPL",
        "CCS/CG",
        "2ª CIME",
        "CPC-I",
        "CPRM",
        "CME",
        "CPE",
        "CPR-I",
        "CPR-II",
        "CPR-III",
        "CPR-IV",
        "CPR-V",
        "CPR-VI",
        "CPR-VII",
        "CPR-VIII",
        "CPR-IX",
        "CPR-X",
        "CPR-XI",
        "CMS",
        "1º BPM",
        "2º BPM",
        "3º BPM",
        "4º BPM",
        "5º BPM",
        "6º BPM",
        "7º BPM",
        "8º BPM",
        "9º BPM",
        "10º BPM",
        "11º BPM",
        "12º BPM",
        "13º BPM",
        "14º BPM",
        "15º BPM",
        "16º BPM",
        "17º BPM",
        "18º BPM",
        "19º BPM",
        "20º BPM",
        "21º BPM",
        "22º BPM",
        "23º BPM",
        "1ª CIPM",
        "2ª CIPM",
        "3ª CIPM",
        "4ª CIPM",
        "5ª CIPM",
        "6ª CIPM",
        "7ª CIPM",
        "8ª CIPM",
        "9ª CIPM",
        "10ª CIPM",
        "11ª CIPM",
        "12ª CIPM",
        "14ª CIPM",
        "BPCHQ",
        "ROTAM",
        "GRAESP",
        "BAC",
        "BOPE",
        "CIPFLU",
        "RPMON",
        "BPGDA",
        "CIPRV",
        "BPA",
        "BPOP",
        "CIEPAS",
        "CIPOE",
        "CIPTUR",
        "HPM",
        "AMC",
        "ODC",
        "LAD",
        "CAF",
        "CMV",
        "CMRA",
        "UPM",
        "1ª USA",
        "BPTRAN",
        "CIAPFEM",
        "1ª ESFORP",
        "CIRP",
        "GEPTUR",
        "GM-ALEPA",
        "CMG",
        "CIOP",
        "13ª CIPM",
        "24º BPM",
        "25º BPM",
        "GOV",
        "FASPM",
        "17ª CIPM",
        "CI",
        "ASCOM",
        "AJG",
        "18ª CIPM",
        "16ª CIPM",
        "FUNSAU",
        "BMUS",
        "2ª USA",
        "3ª USA",
        "4ª USA",
        "6ª USA",
        "7ª USA",
        "8ª USA",
        "9ª USA",
        "GM-TCE",
        "GM-SEGUP",
        "DGO",
        "CINT",
        "DGA",
        "AC",
        "CAPL",
        "GM-JME",
        "DPC",
        "CCP",
        "EPPM",
        "19ª CIPM",
        "26º BPM",
        "27º BPM",
        "28º BPM",
        "29º BPM",
        "30º BPM",
        "31º BPM",
        "32º BPM",
        "33º BPM",
        "34º BPM",
        "35º BPM",
        "36º BPM",
        "20ª CIPM",
        "21ª CIPM",
        "22ª CIPM",
        "23ª CIPM",
        "24ª CIPM",
        "25ª CIPM",
        "26ª CIPM",
        "27ª CIPM",
        "28ª CIPM",
        "29ª CIPM",
        "30ª CIPM",
        "31ª CIPM",
        "32ª CIPM",
        "1ª CIPAMB",
        "2ª CIPAMB",
        "3ª CIPAMB",
        "4ª CIPA",
        "BPRV",
        "BPE",
        "CPR-XII",
        "GM-MP",
        "CM-TJE",
        "CR",
        "GM-TCM",
        "CPA",
        "CPC-II",
        "CPR-XIII",
        "CPO",
        "CPP",
        "CTPM",
        "1ª CIME",
        "15ª CIPM",
        "FN",
        "GM-SEAP",
        "3ª CIME",
        "DETRAN",
        "CCC",
        "CM",
        "CDPM",
        "COI",
        "CPAT",
        "PR",
        "SAS",
        "DPMV",
        "70º BPM",
        "60º BPM",
        "90º BPM",
        "100º BPM",
        "TTT",
        "TE"
      ];            
      function getUnidades() {
        return unidadesArray.map((unidade) => ({ unidade }));
      }
    
      return {
        getUnidades,
      };
    };
export default Unidades;